# This file is used to validate the Chart and sets some values for required fields. It is not used for the deployment.
# Example usage: `helm lint . --values values.lint.yaml`
langfuse:
  encryptionKey:
    secretKeyRef:
      name: langfuse-encryption-key
      key: encryption-key

nextauth:
  secret:
    value: "secretSecret"

postgresql:
  auth:
    password: "secretPassword"

clickhouse:
  auth:
    password: "secretPassword"

redis:
  auth:
    password: "secretPassword"

s3:
  accessKeyId:
    value: "secretAccessKeyId"
  secretAccessKey:
    value: "secretSecretAccessKey"
