langfuse:
  encryptionKey:
    secretKeyRef:
      name: langfuse-encryption-key
      key: encryption-key

nextauth:
  secret:
    value: "secretSecret"

postgresql:
  auth:
    password: "secretPassword"

clickhouse:
  auth:
    password: "secretPassword"

redis:
  auth:
    password: "secretPassword"

s3:
  accessKeyId:
    value: "secretAccessKeyId"
  secretAccessKey:
    value: "secretSecretAccessKey"
