langfuse:
  nextauth:
    secret: secretNextAuthSecret
  salt: secureSalt
  additionalEnv:
  # REDIS
  - name: REDIS_CONNECTION_STRING
    value: "redis://default:secretValkeyPassword@langfuse-valkey-primary:6379/0"
  # CLICKHOUSE
  - name: CLICKHOUSE_MIGRATION_URL
    value: "clickhouse://langfuse-clickhouse:9000"
  - name: CLICKHOUSE_URL
    value: "http://langfuse-clickhouse:8123"
  - name: CLICKHOUSE_USER
    value: default
  - name: CLICKHOUSE_PASSWORD
    value: secretClickhousePassword
  # S3 / MinIO
  - name: LANGFUSE_S3_EVENT_UPLOAD_ENABLED
    value: "true"
  - name: LANGFUSE_S3_EVENT_UPLOAD_BUCKET
    value: langfuse
  - name: LANGFUSE_S3_EVENT_UPLOAD_REGION
    value: auto
  - name: LANGFUSE_S3_EVENT_UPLOAD_ACCESS_KEY_ID
    value: minio
  - name: LANGFUSE_S3_EVENT_UPLOAD_SECRET_ACCESS_KEY
    value: secretMinioPassword
  - name: LANGFUSE_S3_EVENT_UPLOAD_ENDPOINT
    value: "http://langfuse-minio:9000"
  - name: LANGFUSE_S3_EVENT_UPLOAD_FORCE_PATH_STYLE
    value: "true"
  - name: ENCRYPTION_KEY
    value: 0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef
clickhouse:
  auth:
    password: secretClickhousePassword
  resourcesPreset: medium
valkey:
  auth:
    password: secretValkeyPassword
postgresql:
  auth:
    password: secretPostgresPassword
minio:
  auth:
    rootPassword: secretMinioPassword
