{{- if $.Values.langfuse.nextauth.secret.value }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "langfuse.fullname" . }}-nextauth
  labels:
    {{- include "langfuse.labels" . | nindent 4 }}
type: Opaque
data:
  nextauth-secret: {{ $.Values.langfuse.nextauth.secret.value | toString | b64enc }}
{{- end }}