# Validate Langfuse Server settings
{{- if not (has $.Values.langfuse.logging.level (list "trace" "debug" "info" "warn" "error" "fatal")) -}}
    {{- fail "langfuse.logging.level must be one of: trace, debug, info, warn, error, fatal" -}}
{{- end -}}
{{- if not (has $.Values.langfuse.logging.format (list "text" "json")) -}}
    {{- fail "langfuse.logging.format must be one of: text, json" -}}
{{- end -}}

# Validate ClickHouse settings
{{- if ne ($.Values.clickhouse.shards | int) 1 -}}
    {{- fail "Langfuse does not support ClickHouse with mutltiple shards. Set clickhouse.shards to 1 to continue." -}}
{{- end -}}


# Validate Redis settings
{{- if and $.Values.redis.deploy (not (has "--maxmemory-policy noeviction" $.Values.redis.primary.extraFlags)) -}}
    {{- fail "Langfuse requires valkey to be deployed with the `--maxmemory-policy noeviction` flag. Set redis.primary.extraFlags to include this flag to continue." -}}
{{- end -}}


# Validate S3 settings
#   Event Upload
{{- if and $.Values.s3.deploy (not (or $.Values.s3.forcePathStyle $.Values.s3.eventUpload.forcePathStyle)) -}}
    {{- fail "MinIO requires s3 to be deployed with a forcePathStyle. Set s3.forcePathStyle or s3.eventUpload.forcePathStyle to continue." -}}
{{- end -}}

{{- if and (not $.Values.s3.deploy) (not (or $.values.s3.bucket $.values.s3.eventUpload.bucket)) -}}
    {{- fail "S3 bucket must be configured for external provider. Set s3.bucket or s3.eventUpload.bucket to continue." -}}
{{- end -}}

#   Batch Export
{{- if $.Values.s3.batchExport.enabled -}}
{{- if and $.Values.s3.deploy (not (or $.Values.s3.forcePathStyle $.Values.s3.batchExport.forcePathStyle)) -}}
    {{- fail "MinIO requires s3 to be deployed with a forcePathStyle. Set s3.forcePathStyle or s3.batchExport.forcePathStyle to continue." -}}
{{- end -}}

{{- if and (not $.Values.s3.deploy) (not (or $.values.s3.bucket $.values.s3.batchExport.bucket)) -}}
    {{- fail "S3 bucket must be configured for external provider. Set s3.bucket or s3.batchExport.bucket to continue." -}}
{{- end -}}
{{- end -}}

#   Media Upload
{{- if and $.Values.s3.deploy (not (or $.Values.s3.forcePathStyle $.Values.s3.mediaUpload.forcePathStyle)) -}}
    {{- fail "MinIO requires s3 to be deployed with a forcePathStyle. Set s3.forcePathStyle or s3.mediaUpload.forcePathStyle to continue." -}}
{{- end -}}

{{- if and (not $.Values.s3.deploy) (not (or $.values.s3.bucket $.values.s3.mediaUpload.bucket)) -}}
    {{- fail "S3 bucket must be configured for external provider. Set s3.bucket or s3.mediaUpload.bucket to continue." -}}
{{- end -}}
