name: Release Charts

on:
  push:
    branches:
      - main
    paths:
      - 'charts/*/Chart.yaml'
jobs:
  validate:
    name: Validate Helm Chart
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.13.2

      - name: Run helm lint
        run: |
          helm dependency update charts/langfuse/
          helm lint charts/langfuse/ -f charts/langfuse/values.lint.yaml

  release:
    name: Release Helm Chart
    runs-on: ubuntu-latest
    needs: validate
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"